kind: pipeline
name: default

steps:
- name: build
  image: alpine
  environment:
    TERM: dumb
  commands:
  - apk add --no-cache make zsh
  - make

- name: test
  image: alpine
  commands:
  - apk add --no-cache make ncurses zsh
  - make test

- name: deploy
  image: plugins/s3
  settings:
    source: zpe.zwc
    target: /
    bucket: droneci
    access_key: droneci
    secret_key:
      from_secret: s3_key
    path_style: true
    endpoint: https://minio.toast.cafe
  when:
    branch:
    - master
    event:
    - push
